12 commit

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -15,7 +15,7 @@ env:
   SITE_PASSWORD: ${{ secrets.TEST_PASSWORD }}
 
 jobs:
-  build:
+  build-and-push:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -28,24 +28,25 @@ jobs:
         run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-      - name: Build Docker image
+      - name: Pull or Build Docker image
         run: |
-          docker build -t $IMAGE_NAME:$IMAGE_TAG .
-
-      - name: Push Docker image to GHCR
-        run: |
-          docker tag $IMAGE_NAME:$IMAGE_TAG ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
-          docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
+          if ! docker pull ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG; then
+            echo "Image not found, building..."
+            docker build -t $IMAGE_NAME:$IMAGE_TAG .
+            docker tag $IMAGE_NAME:$IMAGE_TAG ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
+            docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
+          else
+            echo "Image pulled successfully."
+          fi
 
   smoke-tests:
     runs-on: ubuntu-latest
-    needs: build
+    needs: build-and-push
     steps:
       - uses: actions/checkout@v3
       - name: Run Smoke Tests
         run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-          docker pull ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
           docker run --rm \
             -e SITE_LOGIN=${{ env.SITE_LOGIN }} \
             -e SITE_PASSWORD=${{ env.SITE_PASSWORD }} \
@@ -61,7 +62,6 @@ jobs:
       - name: Run Integration Tests
         run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-          docker pull ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
           docker run --rm \
             -e SITE_LOGIN=${{ env.SITE_LOGIN }} \
             -e SITE_PASSWORD=${{ env.SITE_PASSWORD }} \
@@ -77,7 +77,6 @@ jobs:
       - name: Run Regression Tests
         run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-          docker pull ghcr.io/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
           docker run --rm \
             -e SITE_LOGIN=${{ env.SITE_LOGIN }} \
             -e SITE_PASSWORD=${{ env.SITE_PASSWORD }} \
